import turtle
#setup
dhouse = turtle.Turtle()
w = 200
h = 100
def go(x,y):
    dhouse.penup()
    dhouse.goto(x,y)
    dhouse.pendown()
    return
dhouse.speed(1000)
#frame
dhouse.fillcolor('yellow')
dhouse.begin_fill()
for i in range(2):
    dhouse.forward(w)
    dhouse.right(90)
    dhouse.forward(h)
    dhouse.right(90)
dhouse.end_fill()
#roof
dhouse.fillcolor('red')
dhouse.begin_fill()
dhouse.left(45)
dhouse.forward(141)
dhouse.right(90)
dhouse.forward(141)
dhouse.end_fill()
#door
go(75,-100)
dhouse.left(135)
dhouse.fillcolor('blue')
dhouse.begin_fill()
for i in range(3):
    dhouse.forward(50)
    dhouse.right(90)
dhouse.end_fill()
#sun
go(400,200)
dhouse.fillcolor('yellow')
dhouse.begin_fill()
dhouse.circle(50)
dhouse.end_fill()
#tree
go(400,-100)
dhouse.fillcolor('brown')
dhouse.begin_fill()
for i in range(2):
    dhouse.forward(30)
    dhouse.right(90)
    dhouse.forward(50)
    dhouse.right(90)
dhouse.end_fill()
#leaf 1
go(340,-50)
dhouse.fillcolor('green')
dhouse.begin_fill()
dhouse.right(180)
dhouse.left(45)
dhouse.forward(64)
dhouse.right(90)
dhouse.forward(64)
dhouse.right(135)
dhouse.forward(90)
dhouse.end_fill()
#leaf 2
go(430,-5)
dhouse.fillcolor('green')
dhouse.begin_fill()
dhouse.forward(90)
dhouse.right(180)
dhouse.left(45)
dhouse.forward(64)
dhouse.right(90)
dhouse.forward(64)
dhouse.right(135)
dhouse.forward(90)
dhouse.end_fill()
#leaf 3
go(430,40)
dhouse.fillcolor('green')
dhouse.begin_fill()
dhouse.forward(90)
dhouse.right(180)
dhouse.left(45)
dhouse.forward(64)
dhouse.right(90)
dhouse.forward(64)
dhouse.right(135)
dhouse.forward(90)
dhouse.end_fill()
#show coordinates
go(200,0)
dhouse.left(180)
dhouse.fillcolor('yellow')
dhouse.begin_fill()
for i in range(2):
    dhouse.forward(70)
    dhouse.right(90)
    dhouse.forward(100)
    dhouse.right(90)
dhouse.end_fill()
go(270,0)
dhouse.fillcolor('red')
dhouse.begin_fill()
dhouse.left(135)
dhouse.forward(141)
dhouse.left(45)
dhouse.forward(70)
dhouse.left(135)
dhouse.forward(141)
dhouse.end_fill()
go(220,-70)
dhouse.left(45)
dhouse.fillcolor('blue')
dhouse.begin_fill()
for i in range(4):
    dhouse.forward(30)
    dhouse.left(90)
dhouse.end_fill()
print(dhouse.xcor())
print(dhouse.ycor())
turtle.done()